# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8af430bc21c14158a02a2538b7bfc77e0b5726501eab790cc58d6dbc88268415999a5bf036a0ab014bac08541ce401d6220a973ce1baf5d03abf60cb7d8e57e

test:
  secret_key_base: 5b0b12e5339cf969cb506a72fecac94c16ff9a25b0487ae877524098325013edb8ce23dbeb87e6323e6785b1c06e14f9522bfc73b446b2f293ea68849267a9e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
